version: '3'
services:
  react:
    image: react
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    depends_on:
      - fastapi

  fastapi:
    image: fastapi
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: shyam
      POSTGRES_PASSWORD: somesecret
      POSTGRES_DB: folio
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
